name: base
channels:
  - Anaconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anaconda=2020.07=py38_0
  - anaconda-client=1.7.2=py38_0
  - anaconda-navigator=1.9.12=py38_0
  - anaconda-project=0.8.4=py_0
  - conda=4.10.3=py38haa95532_0
  - conda-build=3.18.11=py38_1
  - conda-env=2.6.0=1
  - conda-package-handling=1.6.1=py38h62dcd97_0
  - conda-verify=3.4.2=py_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py38h64f37c6_0
  - numpy=1.18.5=py38h6530119_0
  - numpy-base=1.18.5=py38hc3f5095_0
  - numpydoc=1.1.0=py_0
  - pandas=1.0.5=py38h47e9c7a_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py38_1
  - scipy=1.5.0=py38h9439919_0
  - streamlit=0.88.0=pyhd8ed1ab_0
