name: base
channels:
  - Anaconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anaconda=2020.07=py38_0
  - anaconda-client=1.7.2=py38_0
  - anaconda-navigator=1.9.12=py38_0
  - anaconda-project=0.8.4=py_0
  - conda-env=2.6.0=1
  - conda-verify=3.4.2=py_1
  - matplotlib=3.2.2=0
  - numpydoc=1.1.0=py_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py38_1
  - streamlit=0.88.0=pyhd8ed1ab_0
